Review fixed
yelyzaveta-sokolova/CAT-Coding-and-Training pull request #17
Opened 2024-09-09 18:31 UTC by svichkarolga

2024-09-09 21:36 UTC, yelyzaveta-sokolova commented on src/js/reviews.js
> +        console.log(DATA);
удали консоль лог

2024-09-09 21:45 UTC, yelyzaveta-sokolova commented on src/js/reviews.js
> +
всплывающее уведомление есть, заглушки нет. Это в тз есть "Якщо з сервера буде повернута помилка замість переліку відгуків відмалювати текст-заглушку "Not found"/ "

2024-09-09 21:49 UTC, yelyzaveta-sokolova commented on src/css/reviews.css
> +}
добавь на переход цвета рамки при хов и фок на кнопки
transition: color 0.2s cubic-bezier(0.34, 0.78, 0.68, 0.41);
такой у всех

2024-09-09 21:53 UTC, yelyzaveta-sokolova commented on src/partials/reviews.html
> +        <h1 class="title-general">Reviews</h1>
смените пожалуйста на h2, так как h1 мы используем всего один раз на странице.

2024-09-09 21:55 UTC, yelyzaveta-sokolova commented on src/partials/reviews.html
> +        <h1 class="title-general">Reviews</h1>
добавь пожалуйста во все свои классы, кроме общих, название своей секции вначало, потому что, в ином случае, они будут перебиваться

2024-09-09 21:57 UTC, yelyzaveta-sokolova commented on src/partials/reviews.html
> +                        <use href="../img/icons.svg#icon-arrow-right"></use>
убери одну точку ".", в пути к свг, перед тем как пушить

2024-09-09 22:08 UTC, yelyzaveta-sokolova commented on src/css/reviews.css
> +}
добавь отступы между секциями.
для планшета:
.review {
    padding-top: 48px;
    padding-bottom: 48px;
}, а для компьютера
.review {
    padding-top: 82px;
    padding-bottom: 82px;
}

2024-09-09 22:17 UTC, yelyzaveta-sokolova commented on src/css/reviews.css
> +    stroke: hsl(0, 20%, 96%);
А что это за формат?

2024-09-09 22:19 UTC, yelyzaveta-sokolova requested changes
всплывающее уведомление есть, заглушки нет. Это в тз есть "Якщо з сервера буде повернута помилка замість переліку відгуків відмалювати текст-заглушку "Not found"/ " класс невидимости есть в общих.

2024-09-09 22:20 UTC, closed without merging

2024-09-10 07:24 UTC, svichkarolga commented on src/partials/reviews.html
> +        <h1 class="title-general">Reviews</h1>
в яке начало? незрозуміло